---
- name: tests
  hosts: app
  become: yes
  gather_facts: yes
  tasks:
    - name: store date output for timezone check
      command: date
      register: tstamp

    - name: Timezone # Name of the test
      debug:
        msg: "Machine timezone is {{ ansible_date_time.tz }}" # Will print out a message to say what time zone the server is in

    - name: OS
      debug:
        msg: "OS of machine is {{ ansible_os_family }}" # Will show the OS of the machine


    - name: update if debian # Will launch this test if the machine is a debian machine
      ansible.builtin.command: apt update -y # update command for debain machine
      when: ansible_facts['os_family'] == "Debian" # The conditional for the test to run


    - name: update if Centos # Will launch if the machines is a Centos machine
      ansible.builtin.command: yum check-update # update command for centos machine
      when: ansible_facts['os_family'] == "Centos" # The conditional for the test to run

    - name: "Check if Nginx is installed"
      package_facts:
        manager: "auto"

    - name: confirm nginx is installed
      assert:
        that: "'nginx' in ansible_facts.packages" # Will confirm that Nginx is in the location specified

    - name: Check if port 80 is listening
      shell: lsof -i -P -n | grep LISTEN
      register: port_check_80

    - name: confirm port 80 is listening
      assert:
        that: "'*:80 (LISTEN)' in port_check_80.stdout"


    - name: Check if port 3000 is listening
      shell: lsof -i -P -n | grep LISTEN
      register: port_check_3000

    - name: confirm port 3000 is listening
      assert:
        that: "'*:3000 (LISTEN)' in port_check_3000.stdout"
