---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 3
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: akshay2323/node-app
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mongodb://cluster.ip.of.mongo.service:27017/posts
          imagePullPolicy: Always