---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  namespace: default
spec:
  ports:
  - nodePort: 30441
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodeapp
  type: NodePort